[tool.poetry]
name = "trendbridge"
version = "0.1.0a0"
description = ""
authors = ["Álvaro Vázquez Ortiz <alvvazort@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
